# Generated by Django 3.1.4 on 2021-01-02 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseTag', models.CharField(max_length=6)),
                ('courseName', models.CharField(max_length=20)),
                ('categoryName', models.CharField(choices=[('py', 'Python'), ('dl', 'DNN/CV'), ('nlp', 'NLP')], max_length=20)),
                ('phaseName', models.CharField(choices=[('p1', 'Phase 1'), ('p2', 'Phase 2'), ('p3', 'Phase 3')], max_length=20)),
                ('sessionCount', models.IntegerField()),
                ('total_slots', models.IntegerField()),
                ('available_slots', models.IntegerField()),
                ('startDateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseStudentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmx.course')),
            ],
        ),
    ]
