# Generated by Django 3.1.4 on 2021-01-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseName',
            field=models.CharField(max_length=40),
        ),
    ]
