# Generated by Django 3.1.4 on 2021-01-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmx', '0002_auto_20210102_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='categoryName',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='phaseName',
            field=models.CharField(max_length=3),
        ),
    ]
