# Generated by Django 3.1.4 on 2020-12-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empApp', '0002_programmer_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='programmers',
            field=models.ManyToManyField(to='empApp.Programmer'),
        ),
    ]
