# Generated by Django 3.1.4 on 2020-12-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empApp', '0003_auto_20201229_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='project',
            name='programmers',
            field=models.ManyToManyField(to='empApp.Programmer'),
        ),
    ]
